# Sing-Box TProxy Mode Environment Variables

TPROXY_PORT=22026

# Proxy process GID, usually the group ID of the sing-box user
# deploy.sh install 会自动对齐为实际 gid
EXCLUDE_GID=988

# Firewall mark and routing table ID
FWMARK=1
TABLE_ID=100

# nftables table name
NFTABLES_TABLE=sing-box_tproxy4
